### ISSUE TITLE
[BUG] - huge cpu +ram usage when notification window pop up

### ISSUE THREAD

**Issue by tvinki899** [Morph21/MercuryTrade-Community-Fork#109]
![изображение](https://user-images.githubusercontent.com/44946475/148666321-9c3339cc-6191-48de-9a1e-5595b80f64b1.png)

i try enable\disable fore\background fps cap, change numbers
.jar or .exe
reinstall java
clear config folder
=  still same usage
log clear

**Comment by Morph21** [comment]
Does it happens even for test notifications?

**Comment by tvinki899** [comment]
![изображение](https://user-images.githubusercontent.com/44946475/150919270-0a7bb3d5-564d-44cd-89ed-97443b87cba8.png)
if u about this, when i clicked settings window close and nothing happend

**Comment by Morph21** [comment]
Yeah, that's weird. Can you run Mercury trade from CMD and try to open tests once more? You should see any errors in CMD then.

You just need to open CMD inside folder with MercuryTrade.jar the type in console:

java -jar MercuryTrade.jar


And paste any errors here, I will look into it (maybe it's some problem with java version)
Also do you have newest MT version?

**Comment by tvinki899** [comment]
an its from new installed windows 10 same problem 25% CPU

`C:\Users\Admin\Downloads\MercuryTrade.jar\MercuryTrade>java -jar MercuryTrade.jar

JNativeHook: Global keyboard and mouse hooking for Java.
Copyright (C) 2006-2015 Alexander Barker.  All Rights Received.
https://github.com/kwhat/jnativehook/

JNativeHook is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

JNativeHook is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.


`

**Comment by sarathustra** [comment]
i have same issue

**Comment by Morph21** [comment]
@sarathustra can you try to run newest version with .exe file? It should solve the memory issue.
Also original mercury I'm pretty sure won't show notifications

**Comment by sarathustra** [comment]
> @sarathustra can you try to run newest version with .exe file? It should solve the memory issue. Also original mercury I'm pretty sure won't show notifications

it works without problem before this league, now its bugged, but fork mercury bugged aswell, 2-3 pms and then it stop works

**Comment by Morph21** [comment]
@sarathustra 
1. which version of MercuryTrade-community-fork did you use?
2. Did you run it from exe file or from jar file?
3. Are there any errors in logs folder?
4. Which java version do you use?

**Comment by Morph21** [comment]
It looks like totally different issue than te OP created. 

I will look into it.

In the meantime clean installation of mercury trade should fix that issue 

By clean I mean that you need to delete C:/Users/your_username/AppData/Local/MercuryTrade

Before deletion you can backup configuration file inside folder C:/Users/your_username/AppData/Local/MercuryTrade
It contains all settings.

I hope that it helps untill I will solve that issue

**Comment by Morph21** [comment]
Fixed with https://github.com/Morph21/MercuryTrade-Community-Fork/releases/tag/1.2.3
