### ISSUE TITLE
[BUG] - price of item going offscreen

### ISSUE THREAD

**Issue by Weden** [Morph21/MercuryTrade-Community-Fork#112]
The price of item going offscreen.

![javaw_ErTbJIb5oG](https://user-images.githubusercontent.com/7897236/153437527-45a7808b-0446-403e-9f29-0c2d2a13dd11.png)

**Comment by Morph21** [comment]
well.. you can just resize window by grabbing right side of window or change scale of ui

https://user-images.githubusercontent.com/38075691/153441919-3189ea33-fe24-40a8-ab59-ac4d7b312eab.mp4

**Comment by cowsay1** [comment]
Your solution is scrolling wheel every time someone have long nickname? For me this bug makes tool unusable. :(

**Comment by Morph21** [comment]
When you change size of notification or scaling it should be saved so you just need to do it once. But you are free to make better solution for this problem and make a pull request with it.
I don't see better solution for that problem in this particular technology.

**Comment by cowsay1** [comment]
I found solution by using old version (1.1.9)
![image](https://user-images.githubusercontent.com/60675651/153520830-80911777-13c5-4238-a9e6-ba1d80b66742.png)

**Comment by Morph21** [comment]
So I broken one thing while fixing another one...

I will look into it
