### ISSUE TITLE
[BUG] - Whisper button

### ISSUE THREAD

**Issue by GustavoDamm** [Morph21/MercuryTrade-Community-Fork#114]
**Describe the bug**
When clicking to send a whisper the macro refreshes the site

**To Reproduce**
1. Go to 'pathofexile.com/trade'
2. Click on 'live search'
3. Click to send a whisper 

**Expected behavior**
It will alt tab and send a message on game

**Error**
It selects the entire site then refreshes it, not sending the message on game

**Comment by Lokkedian** [comment]
I noticed this happened a lot with the original version as well. Moreso than with the fork, but yes, still an issue.

**Comment by Morph21** [comment]
fixed here https://github.com/Morph21/MercuryTrade-Community-Fork/releases/tag/1.2.4

Keep in mind that in general that function works in this way:
1. You press whisper on trade site
2. MT see that clipboard did changed and try to set poe window to front then give focus to it
3. Enter is pressed, ctrl + a, backspace <- to clear any text in poe chat
4. message is pasted into chat
5. enter is pressed
So if you break gaining focus by pressing on your web browser or another window it won't work, sadly poe doesnt have an api to call it to send a message
