### ISSUE TITLE
Pushbullet

### ISSUE THREAD

**Issue by Djassie18698** [Morph21/MercuryTrade-Community-Fork#117]
I made a pushbullet account and installed it on my pc and phone. After that I entered the pushbullet accestoken into the settings. But when I click test push, nothing happens. Also nothing happens on my phone. Is this an error on my side, or is it not working atm?

**Comment by Morph21** [comment]
it should be working, try to save settings and quit application, start it again and it should work

**Comment by Morph21** [comment]
![image](https://user-images.githubusercontent.com/38075691/162837491-72f9f9c9-e415-4be6-82f2-8352df088a5f.png)

If on the icon you see the red cross then it means that it is disabled

**Comment by Djassie18698** [comment]
Ah I didn't see that, thankyou so much! It works now, what an amazing program!

**Comment by Djassie18698** [comment]
Sorry to open it again, but the test push works, but once I get trade message incoming I don't get a notification in Pushbullet.. not sure why, because the first test message came thru

**Comment by Morph21** [comment]
I'm not sure why is that but if test message is working you can go to settings -> open tests -> random incoming item message.
If that message will be send to your phone then the other ones should be send also

**Comment by Djassie18698** [comment]
Yes! Seems to work again, not sure what happened! I also saw you can see logs? For if it crashes or something. But i only have 2 files in my log folder and they're both not the one with the trade messages. Both are empty
