### ISSUE TITLE
Logs 

### ISSUE THREAD

**Issue by Djassie18698** [Morph21/MercuryTrade-Community-Fork#118]
I also saw you can see logs? For if it crashes or something. But i only have 2 files in my log folder and they're both not the one with the trade messages. Both are empty. I thought i could use the logs after restart to see usernames and offers etc. I added the folder underneath 
![image](https://user-images.githubusercontent.com/51295582/162859582-1282ba67-da46-462d-b1c7-93d31444c732.png)
![image](https://user-images.githubusercontent.com/51295582/162859745-a77fbeb1-e3f3-4ac0-b21f-ce2da5da0078.png)

**Comment by Morph21** [comment]
logs are for showing errors. You can see logs of messages until you shut down MercuryTrade, you can exit path of exile, come back later or if it crashes and you will have log.
Also please use issue tab for errors, you can ask questions about functions of MT on discord https://discord.gg/aG9C8XJ
