### ISSUE TITLE
[BUG] Cannot be used on Korean client (in game language in Eng)

### ISSUE THREAD

**Issue by dchoi44** [Morph21/MercuryTrade-Community-Fork#119]
**Describe the bug**
I think the program requires a path that logs\Clients.txt in it, however, Kakao (Korean PoE publisher) version's log file is like: `C:\Daum Games\Path of Exile\logs\KakaoClient.txt`

**Comment by Morph21** [comment]
correct me if I'm wrong but to my understanding KakaoClient.txt won't log messages from players because of Korean Goverment privacy policy. Isn't that true?

**Comment by dchoi44** [comment]
I actually have heard of the issue so I checked my log file and here it is:


> 2022/02/10 22:39:17 5868171 cff94453 [INFO Client 5572] : You have entered The Twilight Temple.
> 2022/02/10 22:39:18 5869390 3275a31a [INFO Client 5572] [SHADER] Delay: ON
> 2022/02/10 22:42:45 6075984 cff94453 [INFO Client 5572] @From [USERNAME]: Hi, I would like to buy your Ancient Panorama Grave Trough Map (T10) listed for 1 chaos in Archnemesis (stash tab "~b/o 1 chaos"; position: left 1, top 2)
> 2022/02/10 22:43:45 6135921 cff94453 [INFO Client 5572] : You have received an Atlas Skill Point.
> 2022/02/10 22:44:31 6181625 88a909ac [DEBUG Client 5572] Got Instance Details from login server

It seems like log file actually contains incoming whisps, but not sure if this is same as global client log.

**Comment by Morph21** [comment]
Yea, it looks ok. I will try to fix it soon

**Comment by dchoi44** [comment]
So I wrote some lines and have done quick tests.

I think Korean users' messages aren't indeed being logged in the file(includes my very own..), but anyother users' are. 
So it makes MT impossible to trace outgoing trades, which is fine by me.
And any interection with button press ('+', 'thanks') wouldn't send the actual message. Clipboard history indicates that they're copied though.
