### ISSUE TITLE
[BUG] - Invite button does not work on Linux

### ISSUE THREAD

**Issue by UnclePsymon** [Morph21/MercuryTrade-Community-Fork#124]
Hi, i seem to have a similar issue as described here: https://github.com/Morph21/MercuryTrade-Community-Fork/issues/67

**Describe the bug**
Clicking the invite button does not invite the player. Instead the requested item name will pasted and send in the local chat.

**To Reproduce**
0. (Install Linux, download the .jar of Mercury Trade)
1. Launch PoE via Steam
2. Set the game to windowed mode
3. Enable Vulkan
4. Start Mercury Trade
5. Wait for a trade request or use a test notification
6. Click the green plus symbol to invite the player
7. The name of the requested item will be send in local chat

**Expected behavior**
The player should be invited to the group.

**Desktop:**
 - Version 1.2.5

**Additional context**
Here is my recent log: https://pastebin.com/LNhRYM5d
I play PoE on Linux with Steam and Proton. Sadly, not a single overlay for Path of Exile works perfectly fine on any of my (previous) Linux systems. So this might just a Linux related Problem. Right now I combine Mercury Trade with Awakened PoE Trade, which works quite well, besides of game focus issues, but that is absolutely a Linux problem. My bug also occurs when Awakened PoE Trade is not running.
Thank you - and thank you even more for supporting Linux!!

**Comment by Morph21** [comment]
Mercury Trade doesn't support linux. It uses internal Windows dll (microsoft interface functions) to take focus for window and few other things so it won't work on linux sadly.
