### ISSUE TITLE
[FEATURE REQUEST] - Add Enter after item search because it otherwise breaks everything else

### ISSUE THREAD

**Issue by SyrupBuccaneer** [Morph21/MercuryTrade-Community-Fork#125]
**Is your feature request related to a problem? Please describe.**
Clicking on the item adds it to tab search but leaves the field open meaning invite/trade/kick does not work.

**Describe the solution you'd like**
Add Enter because that brings focus away from search and makes the other macros work.

**Describe alternatives you've considered**
Alternatives are excessive to the end-user.

**Additional context**
![Awakened_PoE_Trade_oEwZ29aZaU](https://user-images.githubusercontent.com/72714858/173492261-ea20edfc-9b84-4667-973d-7a4dd0e9f36c.jpg)
Open search after clicking item in box.

**Comment by Morph21** [comment]
fixed in https://github.com/Morph21/MercuryTrade-Community-Fork/releases/tag/1.2.6
