### ISSUE TITLE
[BUG] cannot select game path for kakao poe

### ISSUE THREAD

**Issue by dydxo959** [Morph21/MercuryTrade-Community-Fork#130]
![image](https://user-images.githubusercontent.com/62172402/178977666-4e14dd22-32f1-48ba-b4a3-7d2a296ad383.png)

.exe and .jar didnt work in selecting game path process

im using korean poe(kakao publishing), Win11, and also opend this .exe app as administrator.

**Comment by Morph21** [comment]
Do you know that MercuryTrade won't work with kakao client because of Korean goverment privacy policy?

**Comment by dydxo959** [comment]
crap...
