### ISSUE TITLE
[BUG] - Button customization not working

### ISSUE THREAD

**Issue by looquhs** [Morph21/MercuryTrade-Community-Fork#131]
**Describe the bug**
Everything works fine so far - the only thing i can't change are the response buttons under incoming or outgoing notification. That means i can't change the labels or the text belonging to the button. I even tried to add new buttons - same behaviour. Running it as admin too.

**To Reproduce**
1. Go to 'Settings' 
2. Click on 'Notification panel'
3. Scroll down to 'Incoming notifications" -> resonse buttons
4. Try to change the label or response text

**Expected behavior**
I should be able to change the text.

**Desktop (please complete the following information):**
 - Version 1.2.8

**Comment by Zain890** [comment]
> Same here. Can't edit any text.

Exact same here. No text fields can be edited, regardless of context.

**Comment by Morph21** [comment]
Fixed with release #1.2.9

Let me know if everything works now :)
