### ISSUE TITLE
[BUG] - messages with non-english characters are ignored by MercuryTrade

### ISSUE THREAD

**Issue by Legushka26** [Morph21/MercuryTrade-Community-Fork#133]
**Describe the bug**
When someone sends you a trade message containing non-english characters (name of sender or their message itself, for example in korean, chinese, russian etc) MercuryTrade does not process it and does not activate its overlay trade window with the trade details and buttons.

**Desktop (please complete the following information):**
 - Version 1.3.0

**Comment by Morph21** [comment]
Please post here an example of that message from your Client.txt file which is located in poe folder/logs

**Comment by Morph21** [comment]
It looks like game bug. Messages are logged into Client.txt file by Path of Exile itselft, Mercury Trade only reads from there so if you have message like that
`@to а№‘а№‘___аё™аёІаё‡аёџа№‰аёІаё›аёЈаё°аё—аёІаё™___а№‘а№‘: аёЄаё§аё±аёЄаё”аёµ а№ЂаёЈаёІаё•а№‰аё­аё‡аёЃаёІаёЈа№ЃаёҐаёЃ 9 Exalted Orb аё‚аё­аё‡а№ЂаёЈаёІаёЃаё±аёљ 540 _ аё‚аё­аё‡аё„аёёаё“а№ѓаё™аёҐаёµаёЃ Standard`
in your Client.txt file it wont be possible to convert it into real message. It's also the case for message which aren't logged there. You probably  should find a solution in path of exile forums
