### ISSUE TITLE
[BUG] - No notifications, empty log

### ISSUE THREAD

**Issue by AshDrag0n** [Morph21/MercuryTrade-Community-Fork#136]
**Describe the bug**
Before yesterday i was using old MercTrade on my computer, then i started old MercT on another computer (it was working a year ago, but now - no notification. After reinstalling Java 8..v.. it still doesnt work. Then i found this new version. Also  I reinstalled Java, but it was the same version,. Downloaded jar. file , anzip, start (no option in menu to run as administrator>? why) and all the night notifications were working. Also a guide for fresh start poped up. But now (after sleep and reboot) again i have no notifications. I reinstalled Java, I tried to delete all files with merc trade from my computer to receive the fresh start guide again, but didnt get succes in it. 
Where i can find and delet files to start your application from scratch> ? and may be you know how to fix my problem

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by bleeblee666** [comment]
It's weird, it's been working fine with the latest update. but it's stop showing pop up bar today. I've tried reinstall, use the app's open test, the notifications pop up. For real trade message, nothing showed up.

**Comment by dekadd** [comment]
Same here.

**Comment by Morph21** [comment]
can you post here message from Client.txt file which doesnt work? Maybe Path of exile changed format of texts or something

**Comment by 4d3p7** [comment]
Seems like GGG done something with their log file because non of trading apps are working well since today.

**Comment by 4d3p7** [comment]
> can you post here message from Client.txt file which doesnt work? Maybe Path of exile changed format of texts or something

Outgoing msg:
`2022/08/30 11:46:06 265051671 cff943d6 [INFO Client 13200] @To Kalandra_XuTong: Hi, I'd like to buy your 321 Orb of Chance for my 20 Chaos Orb in Kalandra`

Incoming msg:
`2022/08/30 16:54:32 6649875 cff943d6 [INFO Client 12696] @From <RIPCWC> KINGOFZING: Hi, I'd like to buy your 2 Cursed Crypt Map (T12) for my 4 Chaos Orb in Kalandra`

**Comment by Morph21** [comment]
I will look into it today. I will keep you posted

**Comment by Morph21** [comment]
Sorry guys, I kinda messed up regex so MT wouldnt work on 30 and 31 day of the month, i will put a release in 15 minutes

**Comment by Morph21** [comment]
Fixed with [1.3.1](https://github.com/Morph21/MercuryTrade-Community-Fork/releases/tag/1.3.1)
