### ISSUE TITLE
[BUG] - Commas now break stash searching, click-to-search no longer works

### ISSUE THREAD

**Issue by SyrupBuccaneer** [Morph21/MercuryTrade-Community-Fork#137]
As seen here https://i.imgur.com/RQprdyK.jpeg this was the item to be sold, however it no longer becomes focused in stash when a comma is added. 

This functionality is slightly outdated given a recent update on their end, however in a quad-stash it's not always easy to parse a small highlight vs. the search's functionality of only highlighting that one item. But only searching by name carries with it a potential issue as rares share names regardless of base.

Maybe a regex solution?

**Comment by Morph21** [comment]
Does it work if you remove comma from search box?

**Comment by SyrupBuccaneer** [comment]
> Does it work if you remove comma from search box?

![screenshot-0020](https://user-images.githubusercontent.com/72714858/188287686-8426dcd3-987e-4acc-802e-a9c9b5d68446.png)

Yeah that seems completely fine

**Comment by Reodia** [comment]
Good afternoon. 
Can you please tell me if it is possible to fix this function? 
As I understand, it is enough to supplement the function with automatic deletion of 1 character “,” to make it work correctly.
Thank you in advance for your answer.

**Comment by Morph21** [comment]
Yeah, it should be possible. I will check it out when I'm back from vacation

**Comment by Morph21** [comment]
fixed with latest release
