### ISSUE TITLE
[BUG] - The Betrayal Cheat sheet is not up to dat

### ISSUE THREAD

**Issue by rarestare1** [Morph21/MercuryTrade-Community-Fork#138]
Hello the Cheat Sheet for betrayal is not up to date.
Here is the latest version:
https://i.imgur.com/zsvnVky.png

Please update when you have some time. :)

**Comment by Morph21** [comment]
I will in the next update but you can swap it for yourself. Check readme file inside mercury trade folder

**Comment by Morph21** [comment]
It was updated a while ago now, I must have missed that one. You can always replace that image in your folder to get newest one. Check readme file
