### ISSUE TITLE
[FEATURE REQUEST] - Silent Launch

### ISSUE THREAD

**Issue by mtxfellen** [Morph21/MercuryTrade-Community-Fork#140]
Suggestion to add an option to the settings to launch Mercury Trade silently, without the loading indicator - would be particularly useful if one has their setup configured such that Mercury Trade loads automatically when launching Path of Exile, as it draws over the game and obscures visuals somewhat.

**Comment by Morph21** [comment]
Done in version [1.3.3](https://github.com/Morph21/MercuryTrade-Community-Fork/releases/tag/1.3.3)
