### ISSUE TITLE
[FEATURE REQUEST] - Mercury doesn't work with korean kakao client 

### ISSUE THREAD

**Issue by moral404** [Morph21/MercuryTrade-Community-Fork#143]
sry about lack of english.

I think problem is log file name of korean kakao client 'KakaoClient.txt" not 'client.txt'

two way to solve this problem

1. In setting -general menu, change 'path of exile folder' to 'log file' directly.
2. MercuryTrade automatically choice 'Client.txt' ot 'KakaoClient.txt'

thx

**Comment by Morph21** [comment]
Mercury trade checks if client.txt exists first and if it doesn't then it checks for KakaoClient.txt so it should be working. Keep in mind that while playing Korean version your game won't save any messages (to my knowledge) beacause of Korea privacy regulations
