### ISSUE TITLE
[BUG] - /Hideout macro hotkey is causing unwanted chat messages

### ISSUE THREAD

**Issue by ForsakenScheme** [Morph21/MercuryTrade-Community-Fork#146]
**Describe the bug**
When you hit the hotkey configured for the /hideout macro during filter writing in a tab you will open the chat and eventually send a whisper to the last person you had whispered. I have only tested this in my hideout (which is kinda dumb to do /hideout in your hideout)?

**To Reproduce**
1. In your hideout go to a stash tab or any other tab and click on the "type an item filter"
2. Press your /hideout macro hotkey while typing 
3. Opens chat and display the chat prefix you previously used in open chat
4. If you press the macro again it will send your message into chat (worst case scenario I had is sending a whisper message to a person without wanting to).

**Expected behavior**
Should only open the chat, execute /hideout and display an error message if you're already in hideout (covered by the game) 
Should close the chat afterwards and not send a message

**Screenshots**
Before press of the hideout macro
![image](https://user-images.githubusercontent.com/55463001/223148119-3c1f5500-f7b5-478f-ad12-160d3efff77a.png)

Pressing the hideout macro once 
![image](https://user-images.githubusercontent.com/55463001/223148262-768892db-808b-42cd-bb16-bc45b769a774.png)

Pressing the hideout macro a second time after typing something
![image](https://user-images.githubusercontent.com/55463001/223148527-c9d05330-990c-4cd3-97a2-61a040acab69.png)

**Desktop (please complete the following information):**
 - Version 1.31

**Additional context**
- In my own hideout
- Had previously whispered someone
- Was writing a filter

**Comment by Morph21** [comment]
I just tested it and it doesn't work like you say. However if you have focus on highlight items (blinking cursor) then your chat will be opened because first enter will unfocus the highlight items, then /hideout will be typed but not in chat since its closed then enter will be pressed and chat window will be open.

Just press hideout macro while not typing anything else. There is no work around that since that macro is typing in chat
