### ISSUE TITLE
[FEATURE REQUEST] - Quick plea to get the new /leave functionality in

### ISSUE THREAD

**Issue by mjdvr** [Morph21/MercuryTrade-Community-Fork#148]
I'm always frustrated when I have to manually change the character name every time I want to switch characters to get full trade functionality.

Instead of `/kick {character_name}` we now have `/leave`, which is much more general implementation.
It would be much nicer to have this as the "party leave" command than the self-kick method.

**Comment by toysoldier2012** [comment]
I think we must consider multiplayer team, so probably keep useing /kick

**Comment by Morph21** [comment]
Won't be fixed since that only works when you want to leave and MT can't possibly know if you joined a team or you did invite someone
