### ISSUE TITLE
[FEATURE REQUEST] - Use soundfiles from external folder for easy changing

### ISSUE THREAD

**Issue by Megaddd** [Morph21/MercuryTrade-Community-Fork#149]
Currently it is not possible to change the click/notification/trade alert sounds without rebuilding the app yourself.

It would be very convenient to load these sounds from a folder on runtime, such that changing them is as simple as replacing the sound files in resources.

**Comment by Morph21** [comment]
it is possible.

https://github.com/Morph21/MercuryTrade-Community-Fork/tree/master/resources/app

**Comment by Megaddd** [comment]
Nice! Thanks.
