### ISSUE TITLE
[FEATURE REQUEST] - Overseer independent of PoE

### ISSUE THREAD

**Issue by Barduke** [Morph21/MercuryTrade-Community-Fork#152]
Hi I love the overseer feature from mercury trade and would like to use it in other games as well. would it be possible to make mercurytrade or just overseer run in a general desktop mode, or make it overlay for any exe?

Thanks!

**Comment by Morph21** [comment]
I can compile you a version which can do that. You can try using it and let me know if everything works fine. But it will be MercuryTrade working without poe running not just an overseer exe

**Comment by Morph21** [comment]
Here you go 
https://github.com/Morph21/MercuryTrade-Community-Fork/releases/tag/1.3.3
For standalone experience you need to edit MercuryTrade.l4j.ini file 
change -Dstandalone=false
to this -Dstandalone=true

**Comment by Barduke** [comment]
Thanks again. I just tried it out in a windowed game and it worked flawlessly. Exactly as expected.
