### ISSUE TITLE
[FEATURE REQUEST] - Simplified User Interaction - Unified Action Button

### ISSUE THREAD

**Issue by Vokerr** [Morph21/MercuryTrade-Community-Fork#157]
For an enhanced and streamlined user experience, I propose the introduction of a single button mechanism for both Outgoing and Incoming Notifications. For Outgoing Notifications, this button would sequentially execute the actions: 'thx msg' -> 'Leave Party' -> 'Close Panel'. Similarly, for Incoming Notifications, the button would perform: 'thx msg' -> 'Kick' -> 'Close Panel'. This unified approach will reduce multiple manual steps, offering users a more efficient and intuitive interaction with the platform.

**Comment by Morph21** [comment]
That feature won't be implemented since it would be against TOS of path of exile

**Comment by Vokerr** [comment]
Understood regarding the TOS constraints. Would it be feasible to introduce the ability for users to create custom buttons placed adjacent to each other? This way, users can achieve the desired actions in quick succession without a single button mechanism.

**Comment by Morph21** [comment]
You can set this setting for closing panel on leave/kick here

<img width="416" alt="image" src="https://github.com/Morph21/MercuryTrade-Community-Fork/assets/38075691/89d8a650-b25b-47e9-8bc8-dd5e13d3f6ca">
