### ISSUE TITLE
[BUG] - DND feature issue

### ISSUE THREAD

**Issue by sjxhan** [Morph21/MercuryTrade-Community-Fork#158]
**Describe the bug**
Notification panel from incoming trade whispers still pops up while the DND feature is enabled.

**To Reproduce**
1. Enable DND from the task bar
2. Receive incoming trade whisper

**Expected behavior**
The notification panel shouldn't re-pop up on the screen while (the app's) DND feature is enabled. It seems partially working since the notification panel does hide/show itself when toggling DND on/off. But I would expect the panel to always stay hidden while the feature is enabled.

**Desktop (please complete the following information):**
 - Version 1.3.4

**Comment by Morph21** [comment]
fixed in 1.3.9
