### ISSUE TITLE
[FEATURE REQUEST] - A setting to not hide trades if window is not focused

### ISSUE THREAD

**Issue by TactfulRanger** [Morph21/MercuryTrade-Community-Fork#162]
It would be a nice optional setting to **not** hide MercuryTrade messages if Path of Exile window loses focus.

**Comment by Morph21** [comment]
There is an option to not hide mercury trade in general. 

Check MercuryTrade.l4j.ini file.

I will add a section in wiki about that

**Comment by Morph21** [comment]
Check new wiki page for more info [#wiki](https://github.com/Morph21/MercuryTrade-Community-Fork/wiki/Standalone-mercury-trade)
