### ISSUE TITLE
[BUG] - PoE2 - Trade Wisper on POE2 Trade Site = Incoming and Outcoming Trade window

### ISSUE THREAD

**Issue by Flowex** [Morph21/MercuryTrade-Community-Fork#166]
If i send on the POE2 Trade Site a Direct Wisper for Buying, i becomes incoming and outcoming Trade Window.

**Comment by Morph21** [comment]
which version are you using?

**Comment by Flowex** [comment]
Sorry thats my Fail :( i think i have updated but i dont have it, and with the new 1.4.1 all is working.
Sorry and big thanks for this Tool <3
Merry XMas to you.
