### ISSUE TITLE
[FEATURE REQUEST] - Grid Aligner sizes

### ISSUE THREAD

**Issue by thebeast792** [Morph21/MercuryTrade-Community-Fork#22]
**Is your feature request related to a problem? Please describe.**
The way the grid aligner set up right now makes it hard to set tabs regular vs quad size. It seems to keep a list of a ton of previous tabs I had so I have to go one by one clicking "x" button in the grid aligner or to set a tab quad or not. 

**Describe the solution you'd like**
There should be a feature to just erase all the memorized grid sizes (like a button next to "disable"). Also, whenever you get a trade, when the little tab appears above the stash, it should have a checkbox that lets you swap it between regular and quad size on the fly (and also memorize it in your settings for the future).

**Comment by Morph21** [comment]
Hello, thank you for your feature request.

Can you please add a screen shot of what annoying you?

**Comment by thebeast792** [comment]
![image](https://user-images.githubusercontent.com/14367281/96311851-3d818280-0fbf-11eb-886f-e542c1b2e7ef.png)

**Comment by Morph21** [comment]
Hello, i started working on this feature.

There is a checkbox to specify if tab is a quad tab there. But it shows only when tab is shown for the first time. Isn't it good enough?

**Comment by thebeast792** [comment]
If by first time, you mean it's not in the history list settings, then that would work. But if someone goes and clears that tab from the settings, it should give the option again when that tab is used in a trade.

**Comment by Morph21** [comment]
Yea, that's exactly how it works

**Comment by thebeast792** [comment]
Please make sure it has that "clear all tabs" button, too.

**Comment by Morph21** [comment]
I alreade did :) it's waiting for release
