### ISSUE TITLE
[FEATURE REQUEST] - Notification custom sound

### ISSUE THREAD

**Issue by thebeast792** [Morph21/MercuryTrade-Community-Fork#29]
**Is your feature request related to a problem? Please describe.**
Can't change the notification alert sound. Get annoyed by the old one :P

**Describe the solution you'd like**
Please add a way to configure which sound file to use for the trade notification alert. Maybe have it point to a file in the settings and then allow people to change that file to whatever custom sound they want.

**Comment by Morph21** [comment]
I probably will do it by moving a folder with resources outside of jar/exe file for ppl to be able to change some images/sounds.
