### ISSUE TITLE
[BUG] - Infinite Loading on Startup

### ISSUE THREAD

**Issue by Acidion** [Morph21/MercuryTrade-Community-Fork#3]
**Describe the bug**
If an AppData\Local\MercuryTrade folder does not exist for the current user, you will encounter an infinitely spinning loading circle. Stack trace points to com.mercury.platform.shared.config.MercuryConfigManager.load (Line 118).

**To Reproduce**
1. Don't have and/or remove your AppData\Local\MercuryTrade folder
2. Run MercuryTrade

**Expected behavior**
MercuryTrade should have established the folder it was looking for and started normally.

**Desktop (please complete the following information):**
 - Version 1.10

**Comment by Morph21** [comment]
Workaround found by @Acidion 
_To fix this, you need to make a MercuryTrade folder in your AppData\Local folder.

Windows key -> %appdata% will take you to Appdata\Roaming and then you can navigate up a level to reach Local._

It will be fixed in 1.1.1 release scheduled for friday
