### ISSUE TITLE
[FEATURE REQUEST] - Automatic (Hotkeyless) Whispers

### ISSUE THREAD

**Issue by SmoofBrane** [Morph21/MercuryTrade-Community-Fork#32]
**Is your feature request related to a problem? Please describe.**
I've used other trade macros for a long time and they've all had the ability to just monitor the clipboard to auto-whisper when copying a whisper from trade. Having to press F2 (or any other hotkey) while copying the whisper message is clunky and tedious in comparison.

**Describe the solution you'd like**
A persistent(/hotkeyless) clipboard monitor, such that a hotkey is no longer required to send trade messages.

**Describe alternatives you've considered**
Allow MouseButton1 to be a hotkey, this is a very scuffed workaround and it's definitely not desirable, but I'm not creative enough to come up with anything else.

**Additional context**
Perhaps this should be an optional feature (if it's possible to implement at all) since some might have issues with a persistent clipboard monitor.

**Comment by Morph21** [comment]
It seems possible to do some kind of listener for clipboard and send messages after clipboard content will be a parsable trade site messages. 

I will pin it for 1.1.4 mileston since it needs future research on my side.

Thank you for your contribution.
