### ISSUE TITLE
[BUG] - Part of the keyboard has stopped working.

### ISSUE THREAD

**Issue by HugoZanco** [Morph21/MercuryTrade-Community-Fork#33]
**Describe the bug**
Part of the keyboard (accent buttons like: ' " ` ~ ^) stopped working when I upgraded to the new version 1.1.2.

**To Reproduce**
1. Download MercuryTrade 1.1.2 .exe or .jar
2. Start the application.

**Expected behavior**
The entire keyboard works normally as it does in version 1.1.1.

**Desktop (please complete the following information):**
 - Version 1.1.2

**Additional context**
The keyboard I use is in the Portuguese (Brazil) language and the keyboard model is the QWERTY United States (International).
Until the problem is solved, I will be using version 1.1.1.

**Comment by Morph21** [comment]
Thanks for your feedback. I will look into it

**Comment by Morph21** [comment]
@HugoZanco I found a solution for your problem. Please try latest release and let me know if this solves your problem

**Comment by HugoZanco** [comment]
It's working fine now! Tyvm!

**Comment by Morph21** [comment]
Thank you for your feedback 👍
