### ISSUE TITLE
[FEATURE REQUEST] - PushBullet Notifications

### ISSUE THREAD

**Issue by Hellsing** [Morph21/MercuryTrade-Community-Fork#37]
**Describe the solution you'd like**
I would like to see a PushBullet implementation like this guy did on another fork of MercuryTrade.
https://github.com/Rottenbeer/MercuryTrade/blob/master/app-core/src/main/java/com/mercury/platform/core/misc/PushBulletNotifier.java

**Additional context**
All of the commits regarding PushBullet:
https://github.com/Rottenbeer/MercuryTrade/commit/c7390830afb1c044c73222e13921a7276985c6d1
https://github.com/Rottenbeer/MercuryTrade/commit/9ac8f5f0705c5f4bf515b1005f240787dc2f4536
https://github.com/Rottenbeer/MercuryTrade/commit/9fcbad03c2e7a10a31559be4138ccde021fbaaa1

**Comment by Morph21** [comment]
Hi, thanks for your feedback. I will look into it

**Comment by Morph21** [comment]
I looked into it, I will implement this in next release probably at start of January since I don't have much time in this month

**Comment by Morph21** [comment]
https://github.com/Morph21/MercuryTrade-Community-Fork/releases/tag/1.1.7

**Comment by Dalps1215** [comment]
I have Pushbullet set up on my PC and my phone, and have the Pushbullet enabled on Mercurytrade, how do i configure PB in Merc?

**Comment by Morph21** [comment]
You need to go to pushbullet.com, then log in, go to settings, create access token and copy it, then paste it into mercury trade in settings -> general tab

![image](https://user-images.githubusercontent.com/38075691/108925257-849e1500-763c-11eb-9064-3103de946460.png)
