### ISSUE TITLE
UI disappeared from screen, how to reset?

### ISSUE THREAD

**Issue by Bandoolero** [Morph21/MercuryTrade-Community-Fork#38]
Hello, I placed the UI bar foolishly in an unaccessible place, so when it hid the buttons I could not open settings anymore (because they are offscreen). 

How can I reset the position or open the settings without clicking on the UI?

Thanks in advance!

**Comment by Morph21** [comment]
Right click on mercury trade icon i tray. Then click reset position or settings

**Comment by Bandoolero** [comment]
Thank You so much, you saved me!!!
