### ISSUE TITLE
[BUG] - multiple minor issues in linux beta

### ISSUE THREAD

**Issue by hyperboy124** [Morph21/MercuryTrade-Community-Fork#39]
occiasionally on startup the loading wheel seems to get stuck
various windows don't appear to redraw correctly when info changes for example in settings anything that would create a drop down when unchecked will still have the drop down showing in a glitchy fashion 
various minor graphical issues
glitchy mouse behavior when moving panels
![Screenshot from 2021-01-14 09-40-50](https://user-images.githubusercontent.com/77451829/104613365-c8205f00-564c-11eb-95ee-e496ba237f35.png)
![Screenshot from 2021-01-14 09-41-51](https://user-images.githubusercontent.com/77451829/104613383-cce51300-564c-11eb-9d91-b099d841ded7.png)

![Screenshot from 2021-01-14 09-41-55](https://user-images.githubusercontent.com/77451829/104613404-d0789a00-564c-11eb-855d-ca86d158183a.png)

**Comment by Morph21** [comment]
Did you get any errors? There should be log file in folder where is mercury trade

**Comment by hyperboy124** [comment]
[mercury-app.log](https://github.com/Morph21/MercuryTrade-Community-Fork/files/5816173/mercury-app.log)
from looking at the logs myself i don't think they'll be particularly useful for the listed issues but may help fix the issues with sound support

**Comment by hyperboy124** [comment]
it appears the notifications don't adhear to the Y position of placement though from the conversation on discord i suspect this is intentional at the moment due to a differant bug ... the overseer setup doesn't seem to function correctly either will post an additional log in several hours after playing with it to see if it actually catches any additional errors that might be helpful

**Comment by hyperboy124** [comment]
additional issues ... seems to be multiple window focus issues where the app doesn't grab focus when it should and grabs focus when it shouldn't ... this could be an issue of how my os is setup but the stash grid for locating the item in a trade completely blocks picking up the item

**Comment by hyperboy124** [comment]
[mercury-app.log](https://github.com/Morph21/MercuryTrade-Community-Fork/files/5818954/mercury-app.log)
the weird focus issue seems to be the most major issue with functionality other than overseer appearing to be nonfunctional

**Comment by Morph21** [comment]
Thanks for your feedback, i will look into it

**Comment by hyperboy124** [comment]
![Screenshot from 2021-01-15 06-13-12](https://user-images.githubusercontent.com/77451829/104730456-b350d380-56ff-11eb-9f5b-da80edc5f55f.png)
if you look way in the top right you can see where the notification panel appears to have had a slight issue when buying an item ... seems mostly graphical and generally not major and probably even related to the image refresh bug noted already but a bugs a bug ... weirdly it doesn't do this on sells only buys

**Comment by Morph21** [comment]
I fixed most of issues here, some are impossible to fix. As of now, linux,macOS support will be discontinued, you can read more about that here: https://github.com/Morph21/MercuryTrade-Community-Fork/wiki/Linux-macOS-not-working-manifest
