### ISSUE TITLE
[FEATURE REQUEST] - Taskbar and notification panel transparent

### ISSUE THREAD

**Issue by Schn1ek3** [Morph21/MercuryTrade-Community-Fork#43]
I would prefer to make the taskbar and notification panel a little more transparent. Would that be possible?
Possibly also the color can be adjusted.

**Comment by rmelcer** [comment]
If you're using Linux or MacOS, see https://github.com/Morph21/MercuryTrade-Community-Fork/wiki/Linux-macOS-not-working-manifest.

On Windows, you can adjust transparency via Settings -> General -> Max opacity.

**Comment by Schn1ek3** [comment]
Thank you :)
