### ISSUE TITLE
[FEATURE REQUEST] - Deduplicate automatic trade whispers

### ISSUE THREAD

**Issue by rmelcer** [Morph21/MercuryTrade-Community-Fork#46]
**Is your feature request related to a problem? Please describe.**
When a MercuryTrade user uses PoE Overlay's shortcuts (/hideout, /kick), MT will re-whisper old trade messages.

Ex:
- User copies a trade message ("Hi, I'd like to buy your foo")
- (good) MercuryTrade sends the trade message automatically
- User uses a /command macro (ex: PoE Overlay's /hideout)
- PoE Overlay runs "/hideout" in PoE, (changing the clipboard) then
- returns the clipboard to the old state (changing the clipboard again)
- The clipboard is again ("Hi, I'd like to buy your foo")
- (bad) Mercury Trade resends the trade message again

Other minor problem:
1. When MT starts or restarts, if your clipboard contains an old trade
message, MT will resend it.
2. When the user refreshes their item search page, they may lose track
of which items they have already messaged. In this case, if they have
already messaged for an item, MT will ping the seller again.

**Describe the solution you'd like**
I'd like MT to check the clipboard's contents against its history of previous trades, and skip resending the whisper if it was already sent recently (last 5-10 messages)
**Describe alternatives you've considered**
I tried to make this myself and it seemed to be working (#45), but after clearing my history, it broke again. When I dug into it more, it seems that MT only saves the message (Hi I'd like to buy your 2 chaos for my 10 alchemy) without including the recipient's name. This makes it impossible to de-duplicate across similar trades to different users - for example with multiple currency trades.
**Additional context**

**Comment by Morph21** [comment]
you know that you can use /hideout macro in MT also? Just bind the shortcut
