### ISSUE TITLE
[FEATURE REQUEST] - Plugin feature?

### ISSUE THREAD

**Issue by Schn1ek3** [Morph21/MercuryTrade-Community-Fork#47]
It would be nice if there was the possibility to expand "Overseer" with plugins and overlays such as "Awakened PoE Trade" or "Chaos Recipe Enhancer" could be added as a plugin without having to install multiple programs. 
So you could offer "Overseer" as a standalone program and "MercuryTrade" and others could be added as needed.

**Comment by Morph21** [comment]
I'm not sure what you mean by plugins. Each of the applications that you mentioned are written in different programming language so it's not possible to do some kind of plugins managament. Only thing that would be possible to just make some launcher inside MercuryTrade which would be able to launch these applications. But still they would work as sepparate applications.

**Comment by Schn1ek3** [comment]
My idea was that you can program plugins that you can intrigrate there. Such as the standalone programs mentioned, for example. So everyone could expand the Overseer program with further functions and put the program together as everyone wants.  
Sorry for my bad English :D

**Comment by Morph21** [comment]
It's is possible to do that right now. Just download the source code from github, then do a pull request with your changes. After aproval it will be integrated into MT. I don't see any benefit from plugins system as there are no much people which will make them anyway
