### ISSUE TITLE
[FEATURE REQUEST] - Heist Overlay

### ISSUE THREAD

**Issue by B14d3r11** [Morph21/MercuryTrade-Community-Fork#48]
I would like to request that the Heist chart 

From https://external-preview.redd.it/h1Dw4KLBUaJZLZVLyMe4MsmmEWRVlwOS0y-ymTlGvpk.jpg?auto=webp&s=931857b239ec813b461b9768da7debcba62cc6d3

be added in a similar fashion to how the Betrayal stuff is? Maybe make it so the ? button opens up a little branching button for two more buttons above it that have Syndicate and Heist to press to choose which one to open?

Also adding the ability to hotkey said Heist window like the beytrayal one would be super useful

**Comment by Morph21** [comment]
Done in 1.1.8 release
