### ISSUE TITLE
[BUG] - Notification panel doesn't work

### ISSUE THREAD

**Issue by SailorDra** [Morph21/MercuryTrade-Community-Fork#49]
Notification panel doesn't work when there is a trade offer or when i test it doesn't drop down  even thought i'm in windowed fullscreen or windowed.

Windows 
 - Version 1.1.5

**Comment by Morph21** [comment]
Are you running PoE on Vulkan?

![image](https://user-images.githubusercontent.com/38075691/105986450-404f4180-609d-11eb-949e-6241daa2fce6.png)

**Comment by SailorDra** [comment]
No i'm in the DirectX11

**Comment by Morph21** [comment]
Do you hear the sound of incoming notification?
You can check if positioning is correct also reset MT to default position.
Do you see other windows? like settings or bar with icons?

**Comment by Morph21** [comment]
btw you should try vulkan, preformance is so much better

**Comment by SailorDra** [comment]
mmmm let my switch to vulkan and try again if i still have the same problem i'll let you know

**Comment by Morph21** [comment]
you can also try to use vulkan support with directx11 but only in windowed fullscreen. It basically changes some window settings and should help with displaying notifications, windows, etc.

**Comment by SailorDra** [comment]
regarding your previous questions yes i do hear the sound notification and i only see the bar with the icons.
Also i just checked at vulkan with support and direct with support and still nothing

**Comment by Morph21** [comment]
did you checked the .log file? It should be in a folder where MercuryTrade.exe is, inside "logs" folder

**Comment by SailorDra** [comment]
sry for late reply i'm usesing the .jar version i'l try now the .exe

**Comment by SailorDra** [comment]
test still not working and in the logs folder there is a single .log notepad that it's completely empty

**Comment by Morph21** [comment]
you can also run MercuryTrade with a parameter -dev

It will cause MT running without need of PoE  so you can try that out. Maybe it will help.

**Comment by Morph21** [comment]
also try to restore defaults

![image](https://user-images.githubusercontent.com/38075691/106002652-ac3ba500-60b1-11eb-9b0e-11c494c7dfcf.png)

**Comment by SailorDra** [comment]
i restored to defaults and it didn't work unfortunately
if possible can you tell me how to do the parameter??

**Comment by Morph21** [comment]
Here is of .exe file with shorcut

https://www.digitalcitizen.life/shortcut-arguments-parameters-windows/

**Comment by SailorDra** [comment]
did it and the tests still don't work :(

**Comment by SailorDra** [comment]
ok so i restarted everything and restored to defaults as the default positions it works i'll try positioning them as i like and see if it works

**Comment by SailorDra** [comment]
yep it doesn't work at the positions i like them is there a solution to that?

**Comment by Morph21** [comment]
do you have an uncommon monitor resolution/ratio or something that could matter there? I don't have this problem so it's hard to find out the issue there

**Comment by SailorDra** [comment]
no my resolution is 1920*1080 i have 3 screens but i don't think that's the problem because at default positions it saws at the corect monitor

**Comment by Morph21** [comment]
Can you post a screenshot of positions of MT elements which you want to set up?

**Comment by SailorDra** [comment]
ok give me a sec

**Comment by SailorDra** [comment]
![Screenshot (6)](https://user-images.githubusercontent.com/51661006/106014966-aef4c500-60c6-11eb-9d7c-a39d682ece5a.png)
here

**Comment by Morph21** [comment]
Can i send you a jar file in a moment for you to try it out?

**Comment by SailorDra** [comment]
YES!!!!!!!!!!!!!!! it finally works thank you alot for helping me <3

**Comment by Morph21** [comment]
I'm glad that i could help you. This is very weird issue and fixing it kinda breaks possibility of upwards notifications so in future release i will probably make an option in settings to turn on/off notification support
