### ISSUE TITLE
[BUG] - jni error has occured

### ISSUE THREAD

**Issue by Morph21** [Morph21/MercuryTrade-Community-Fork#5]
Possible solution:
https://stackoverflow.com/questions/22381202/a-jni-error-has-occurred-please-check-your-installation-and-try-again-in-eclips

If someone also have that error please add a comment here describing steps to reproduce and java version that you have installed

**Comment by thebeast792** [comment]
I had this error but got it to work after updating/re-installing java runtime environment at https://www.java.com/en/download/

**Comment by Morph21** [comment]
Thanks for feedback. I'm closing it now because solution was found.

If someone will have same error please try install java8 from link: https://www.java.com/en/download/
It's better to use exe file on installing.
