### ISSUE TITLE
[BUG] - Mouse overlay gets stuck on mouse regardless of location

### ISSUE THREAD

**Issue by Skiazo** [Morph21/MercuryTrade-Community-Fork#51]
**Describe the bug**
floating information hover text follows mouse movements and doesn't go away. even if hovered over different button, text will change but still follows mouse. as if moue movements not detected.

**To Reproduce**
1. unable to pin point specific actions. happens when ever trading super fast.
2. trading fast. confirmed MBXtreme also has this issue.

**Expected behavior**
updates mouse location thus turning off information hover text

**Screenshots**
https://www.twitch.tv/videos/893986569 
https://www.twitch.tv/videos/893997644

Log shows no issue when this happens.

**Desktop (please complete the following information):**
 - Version [1.1.5.2]

**Comment by Skiazo** [comment]
i can get more video to review if you would like. happens often while trading fast

**Comment by Morph21** [comment]
I will try to fix it and will add a setting which will allow you to disable tooltips for notifications.

**Comment by Skiazo** [comment]
You are awesome thank you!!

**Comment by Skiazo** [comment]
Was able to reproduce consistently with the test incoming messages. Kick from party and then add player fast or trade fast then kick player add player will cause it to happen.

**Comment by Morph21** [comment]
@Skiazo Hi, i released a new version of MT. Check if your bug is fixed now: https://github.com/Morph21/MercuryTrade-Community-Fork/releases/tag/1.1.6

**Comment by Skiazo** [comment]
Seems to work great! thanks for fixing this! If it happens again i will let you know here :) Thank you!
