### ISSUE TITLE
[BUG]Sound doesnt work

### ISSUE THREAD

**Issue by Rallyket** [Morph21/MercuryTrade-Community-Fork#54]
The sound doesnt work for me.
The click sound doesnt work and the trade sounds doesnt work.
I have the newest one.

**Comment by Rallyket** [comment]
It looks like it fixed it, i just had to assign my soundcard\dac to the application in the advanced options for sound, in the app volume\device settings.

**Comment by Morph21** [comment]
im glad that you solved your issue
