### ISSUE TITLE
[FEATURE REQUEST] - Macro

### ISSUE THREAD

**Issue by DarkStas** [Morph21/MercuryTrade-Community-Fork#55]
Please add the creation and configuration of custom macros and also give the ability to modify already created macros and create groups from macros commands (pm text, trade, end of trade, etc.).

**Comment by Morph21** [comment]
What do you mean by macro? Your description is not good enough for me to understand what would you like to be implemented into MT

**Comment by Morph21** [comment]
Closing due to no response for followup question
