### ISSUE TITLE
[BUG] - Duplicate trade messages

### ISSUE THREAD

**Issue by casillias** [Morph21/MercuryTrade-Community-Fork#57]
**Describe the bug**
Sometimes after you send trade request and price check other item, MT sends trade request. Restarting MT makes it send message again????????

**To Reproduce**
1. Send trade request
2. Price-check an item/go to your HO/restart MT
3. See error

**Expected behavior**
Not to duplicate messages.

**Desktop (please complete the following information):**
 - Version 1.1.7

**Additional context**
HALP!! Hate AHK and do not want other trade helper.

**Comment by Morph21** [comment]
What you mean by price-check item? MT does not have this function. Which additional addon do you use?

**Comment by casillias** [comment]
Ye, sorry confused them) Awakened poe trade. CTRL+D price-check there and if I whispered someone via MT before, usually I duplicate it after clicking ctrl+d

**Comment by HiPoEGH** [comment]
This is still a problem.
If you try to "resend message", while having any whisper message that MT recognizes in the clipboard still, it will duplicate it.
I suggest a fix that AFTER MT has sent any message, clear the clipboard data.
It is polling for that data anytime the clipboard changes.
