### ISSUE TITLE
[FEATURE REQUEST] - Standalone Overseer (even if forked from MT)

### ISSUE THREAD

**Issue by rogueyoshi** [Morph21/MercuryTrade-Community-Fork#6]
**Is your feature request related to a problem? Please describe.**
Overseer is extremely useful but many people think it should be it's own thing. I personally play SSF so I don't use the MT aspects anymore but would use Overseer.

**Describe the solution you'd like**
Split Overseer and MT into two separate apps.

**Additional context**
Not much else. Would it be intensive, I wonder?

**Comment by Morph21** [comment]
I will move that issue to latest release. It will require massive amout of work to be done so I'm not sure if it will be done soon

**Comment by Morph21** [comment]
Sorry, that feature requires too much amount of work so it won't be done in near future. If you want to try do it by yourself you are welcome to do it and push a pull request
