### ISSUE TITLE
[FEATURE REQUEST] - Party invite request history or notification

### ISSUE THREAD

**Issue by Zakhaev31** [Morph21/MercuryTrade-Community-Fork#62]
Last night, when i was buying items, i was on the trade web searching similar items cuz ppl sometimes dont respond the trade.

Then when i back to the game, i saw an invite request, but dissapear, and i lost the trade because idk, who was between the 10 ppl i msg
the game in background dont flash when u receive a party invite, i would be great if we can open a panel for checking last party invite request or get a notification when someone invite us!

Cheers and Thanks for keeping alive this great application

**Comment by Morph21** [comment]
Information about getting an invite isn't logged into Client.txt file by poe so it's impossible to detect who did invite you
