### ISSUE TITLE
[BUG] - Windows 10 Trojan Warning.

### ISSUE THREAD

**Issue by emirkmo** [Morph21/MercuryTrade-Community-Fork#64]
**Describe the bug**
Attempting to download the latest .jar release, using Edge, Windows Defender warns with the following:

Trojan:Win32/Phonzy.A!ml

**To Reproduce**
1. Go to releases
2. Click on latest.jar
3. Save
4. Windows defender will quarantine and remove the file.

**Additional context**
What's the deal? Why is there a trojan warning? I don't get it from the original version.. Will test again to be sure.

**Comment by Morph21** [comment]
There is nothing named latest.jar in that repository so I don't know what are you clicking on.
Besides, scanning file named MercuryTrade.jar.zip or MercuryTrade.jar with windows defender does not shows any malwares.
You should look for issues on your PC. Maybe it's infected already and simply showing you false informations.

**Comment by Morph21** [comment]
Here you have images from online scanner, i believe that there are multiple ones which can scan files for viruses. So next time try these first...

![image](https://user-images.githubusercontent.com/38075691/113789730-0014db00-9740-11eb-941f-a799fff22111.png)
![image](https://user-images.githubusercontent.com/38075691/113789750-0dca6080-9740-11eb-888d-fa0debc3286f.png)

**Comment by emirkmo** [comment]
I ran the same and nothing was found, so I think it's a mistake by Windows Defender. By latest .jar I just meant the latest release version.
