### ISSUE TITLE
[BUG] - Jar embeds android code

### ISSUE THREAD

**Issue by krissrex** [Morph21/MercuryTrade-Community-Fork#66]
**Describe the bug**
Is this an android app apk-file?
It is unclear why the jar has the `android/`, `dalvik/` and `AndroidManifest.xml` files inside it.
Most likely, a third party dependency is dragging this along, bloating the jar file.

**To Reproduce**
1. Download the jar
2. Rename the `MercuryTrade.jar` to `MercuryTrade.zip`
3. Extract into a folder.

**Expected behavior**
No bloat code.

**Screenshots**
![image](https://user-images.githubusercontent.com/7364831/115269989-27a27500-a13c-11eb-8bc6-3b29aa320e09.png)

**Desktop (please complete the following information):**
 - Version 1.1.7

**Comment by Morph21** [comment]
There is no AndroidManifest file inside MercuryTrade code. There are a few dependecies which are used and probably one of them includes AndroidManifest.xml. I don't really see an issue here

**Comment by krissrex** [comment]
It's being added by `app` and `app-ui` from the dependency `org.pushingpixels:trident:1.3` ([github](https://github.com/kirill-grouchnikov/trident)). Trident is an archived repo, now [radiance](https://github.com/kirill-grouchnikov/radiance) (java9+).

Trident has some android interpolators in `org.pushingpixels.android`, but none are used here.  
The `app-ui` uses trident for `Timeline`, `TimelineCallback`, `Spline` etc to do animations.

Trident also pulls in `org.eclipse.swt.gtk.linux`.

Side note: Trident is BSD-lincense (https://github.com/kirill-grouchnikov/trident/tree/v1.5.00) but mercury trade does not include this license as [stated](https://opensource.org/licenses/bsd-license.php): `2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.`

I can solve this by adding `exclusions` in the `pom.xml`, as long as Trident do not import those classes.
