### ISSUE TITLE
[BUG] - Invite player button pasting in item name

### ISSUE THREAD

**Issue by Murlocks** [Morph21/MercuryTrade-Community-Fork#67]
**Describe the bug**
Pressing the '+' button doesn't invite player as expected. Instead the item's name is pasted and entered into chat. This only seems to happen for item trades, maps & currency work just fine.

**To Reproduce**
1. Press '+' button.
2. Observe that the item name is pasted into chat.

**Expected behavior**
Player whispering trade offer is invited into party.

**Desktop (please complete the following information):**
1.1.7

**Additional context**
There seems to be something competing with the expected behavior... When I spam the '+' button, *sometimes* it works as expected and sends out the /invite command, but most of the time it pastes the item name. I am NOT using PoeTradeMacro which was mentioned in the common issues page...

**Comment by Morph21** [comment]
I can't reproduce your issue. Are you using any other 3rd party appliactions for PoE? Also it would be helpfull if you can paste here exact log message when that problem occur.

**Comment by Morph21** [comment]
closed due to no answer for followup question
