### ISSUE TITLE
huge fps drops when a popup is open

### ISSUE THREAD

**Issue by baottousai** [Morph21/MercuryTrade-Community-Fork#68]
I noticed my game being extremely laggy when I have something open like a trade notification panel until it's closed
Using DirectX and a RX 470 with engine multithreading

**Comment by krissrex** [comment]
Have you focused the window (ie. clicked on it), and are you using background fps with a very low setting? 
![image](https://user-images.githubusercontent.com/7364831/117076062-19f11000-ad36-11eb-94ee-95a2a6a2eddf.png)

**Comment by Morph21** [comment]
As @krissrex said, you need to set up background fps cap higher
