### ISSUE TITLE
[BUG] - Leave from party on Outgoing notifications does not work

### ISSUE THREAD

**Issue by alumriel** [Morph21/MercuryTrade-Community-Fork#69]
**Describe the bug**
When attempting to use the "leave from party" button on Outgoing notifications, I always get an error "the target of this operation was not a party member", while I'm still clearly in the party (other person invited me)

**To Reproduce**
1. Go to 'Outgoing notification'
2. Click on 'red run away button'
3. Error will show in the chat window.

**Expected behavior**
I would expect this button to remove me from any group I'm currently in, regardless of who created the group, but I'm not sure if there is a /slash command for this.

**Comment by krissrex** [comment]
Have you set your username in the mercury trade settings? I believe that is required.

**Comment by Morph21** [comment]
You need to set properly your current character name inside mercury trade settings
