### ISSUE TITLE
[FEATURE REQUEST] - Put Trades on Hold

### ISSUE THREAD

**Issue by Tsekeflime** [Morph21/MercuryTrade-Community-Fork#70]
**Is your feature request related to a problem? Please describe.**
When mapping or fighting a boss i like to put my trades on hold with a message like "Currently in a map. Do you want me to whisper you back when i am finished?". At this point i would like to have the option to turn down the opacity of the notification panel so it doesn't block any view on the screen.

**Describe the solution you'd like**
A solution i'd like is having the option to hide the window when using response buttons. And only show window again when hovering over the invisible window or when another trade whisper comes in.

**Describe alternatives you've considered**
Instead of only hiding the window to have the option to change between opacity while on 'hold' mode. Or to minimize it into a smaller window. 

**Additional context**
-

**Comment by Morph21** [comment]
since 1.3.9 there was added a buton to task bar to hide messages, it will stay hidden until new message will come or you will alt tab to other program and alt tab to poe
