### ISSUE TITLE
[BUG] - Tutorial window is not resizable

### ISSUE THREAD

**Issue by ythuriel** [Morph21/MercuryTrade-Community-Fork#73]
**Describe the bug**
Tutorial windows are not resizable and all the text can't fit inside deafault size one.

**To Reproduce**
1. Go to "Settings"
2. Click on 'Open tutorial'
3. Tab out to PoE window
4. Progress  to the last screen
5. Text you can see is cut in the middle of lines height

**Expected behavior**
Text should be adjusted to the window size automatically or window should be resizable or the text should be scrollable.

**Screenshots**
https://imgur.com/GeWJdNe

**Additional context**
I'm using windowed fullscreen mode of PoE which may have and influence on this.

**Comment by Morph21** [comment]
Fixed with https://github.com/Morph21/MercuryTrade-Community-Fork/releases/tag/1.2.3
