### ISSUE TITLE
[BUG] - Betrayal chart is outdated

### ISSUE THREAD

**Issue by krissrex** [Morph21/MercuryTrade-Community-Fork#74]
**Describe the bug**
The chart of what is good and bad for betrayal is outdated, compared to the chart in e.g. [awakened-poe-trade](https://github.com/SnosMe/awakened-poe-trade). 

The image is located at https://github.com/Morph21/MercuryTrade-Community-Fork/blob/master/app-ui/src/main/resources/app/helpIGImg.png .

**To Reproduce**
1. Start mercury trade
2. Press `?` button (`"See IG help"`)  
![open IG help](https://user-images.githubusercontent.com/7364831/118016769-13762000-b356-11eb-9d75-f02cc5778fe3.png)

**Expected behavior**
A chart updated for 3.14 should be shown.

**Screenshots**

![outdated](https://github.com/Morph21/MercuryTrade-Community-Fork/blob/master/app-ui/src/main/resources/app/helpIGImg.png?raw=true)

Awakened-poe-trade uses this one:
![awakened-poe-trade](https://user-images.githubusercontent.com/7364831/118017362-d0687c80-b356-11eb-875c-c52abe6aff4a.png)

**Desktop (please complete the following information):**
 - Version 1.1.7

**Comment by krissrex** [comment]
To be honest, I don't know if this is the kind of functionality that MercuryTrade should provide or not.
Perhaps better to keep it trade-related only, and let other apps deal with cheat sheets?

**Comment by Morph21** [comment]
fixed with today release, Added possibility to change it for each user check README file inside folder "MercuryTrade/resources/app"
