### ISSUE TITLE
[BUG] - Java 11 NoClassDefFoundError: com/sun/awt/AWTUtilities

### ISSUE THREAD

**Issue by Barragek0** [Morph21/MercuryTrade-Community-Fork#75]
> 2021-05-18 02:14:57.160 [main] ERROR ErrorHandler - java.lang.NoClassDefFoundError: com/sun/awt/AWTUtilities
> 
> 	at com.mercury.platform.ui.adr.components.AbstractAdrFrame.<init>(AbstractAdrFrame.java:32)
> 	at com.mercury.platform.ui.adr.components.AbstractAdrComponentFrame.<init>(AbstractAdrComponentFrame.java:23)
> 	at com.mercury.platform.ui.adr.components.AdrSingleComponentFrame.<init>(AdrSingleComponentFrame.java:18)
> 	at com.mercury.platform.ui.adr.components.factory.frame.SingleFrameProvider.getFrame(SingleFrameProvider.java:16)
> 	at com.mercury.platform.ui.adr.AdrManager.lambda$initComponents$11(AdrManager.java:297)
> 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
> 	at com.mercury.platform.ui.adr.AdrManager.initComponents(AdrManager.java:283)
> 	at com.mercury.platform.ui.adr.AdrManager.load(AdrManager.java:63)
> 	at com.mercury.platform.ui.manager.FramesManager.start(FramesManager.java:150)
> 	at com.mercury.platform.AppMain.main(AppMain.java:66)
> Caused by: java.lang.ClassNotFoundException: com.sun.awt.AWTUtilities
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
> 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
> 	... 10 more

**Comment by krissrex** [comment]
It does not support java 11, only 8.
You can run it with the workarounds shown in https://github.com/Morph21/MercuryTrade-Community-Fork/issues/65 .

Make a shortcut with a target like:
```
"C:\Program Files\AdoptOpenJDK\jdk-11.0.3.7-hotspot\bin\javaw.exe" --illegal-access=permit -jar MercuryTrade.jar
```

**Comment by Morph21** [comment]
com/sun/awt was removed from MT so it should be possible to use openjdk now. But atm it's still not possible to use higher version of java than 8. Will be fixed in future
