### ISSUE TITLE
[BUG] - Chat scanner may stop working after 2021

### ISSUE THREAD

**Issue by krissrex** [Morph21/MercuryTrade-Community-Fork#76]
**Describe the bug**
The code has a `//todo` where messages have their date extracted.
The code only checks messages with 2019, 2020, and 2021 for a date.

**To Reproduce**
1. Live in 2021
2. Get an incoming message

**Expected behavior**
Chat messages should be detected after 2021.

**Desktop (please complete the following information):**
 - Version 1.1.7

**Additional context**

com/mercury/platform/core/utils/MessageFileHandler.java:77

https://github.com/Morph21/MercuryTrade-Community-Fork/blob/a5d85d2f4d89036225dad08cb66f5453a84bbd12/app-core/src/main/java/com/mercury/platform/core/utils/MessageFileHandler.java#L77

**Comment by Morph21** [comment]
fixed with todays release 1.1.8
