### ISSUE TITLE
[FEATURE REQUEST] - Show that item names in incoming notifications can be clicked to search stash

### ISSUE THREAD

**Issue by krissrex** [Morph21/MercuryTrade-Community-Fork#77]
**Is your feature request related to a problem? Please describe.**
If you click the item name in a notification, mercury will search your stash tab for it by auto-filling the search field.
I have used mercury for a long time, and had no idea it could do this.
I guess there are others too, that don't know.

**Describe the solution you'd like**
A visual indication that the item can be clicked to search.

**Describe alternatives you've considered**

* A 🔎 icon next to the item name
* A tutorial hint that says it can be clicked
* A hover tooltip on the item that says "click to search stash"
* A less visible text that says "click to search" or similar, after or below the item name
* A button (like the join/trade/kick) for "search stash"

Anything visual, really. I did not think about mousing over the item myself.

**Additional context**
I am talking about incoming trades, and the notification popups.

**Comment by Morph21** [comment]
In last release tooltips were fixed so it's showing now
