### ISSUE TITLE
[BUG] - 

### ISSUE THREAD

**Issue by ThisIsntDeception** [Morph21/MercuryTrade-Community-Fork#80]
For some reason the Notification Panel no longer pops up. 

Tried testing with individual tests included in the program but it doesn't work.

Have redownloaded the file and reinstalled Java but it doesn't seem to help

**Comment by krissrex** [comment]
What is your operating system?
What is your java version?
Are you using Vulcan or DX 11?
Is anything visible from MercuryTrade at all?

If you start the jar in a terminal/cmd, you can see any error logs: `java -jar MercuryTrade.jar`

**Comment by Morph21** [comment]
Closed because of inactivity
