### ISSUE TITLE
[BUG] - Item "A Note in the Wind" is parsed incorrectly

### ISSUE THREAD

**Issue by krissrex** [Morph21/MercuryTrade-Community-Fork#82]
**Describe the bug**
When selling the divination card `A Note in the Wind`,
the trade popup will list `A Note` and no price.

**To Reproduce**
1. List `A Note in the Wind` for sale
2. Receive an incoming tade offer from another player
3. Look at the Mercury Trade popup
4. Notice the wrong name and missing price

**Expected behavior**
The trade popup should show the correct, full name of the item, and list the price.

**Screenshots**
![image](https://user-images.githubusercontent.com/7364831/127926742-3fdbef0a-2fc4-4baf-b436-19edd0d474cb.png)

**Desktop (please complete the following information):**
 - Version 1.1.7

**Additional context**
Trade message:
```
@From ChaendrianLotus: Hi, I would like to buy your A Note in the Wind listed for 26 chaos in Expedition (stash tab "Bitcoins"; position: left 11, top 12)
```

**Comment by Morph21** [comment]
This is kinda a bummer because regex will think that "in" inside item name is an keyword before league name

**Comment by Morph21** [comment]
fixed with https://github.com/Morph21/MercuryTrade-Community-Fork/releases/tag/1.2.0
