### ISSUE TITLE
Bug since years - Stuck Button somewhere on the screen[BUG] - 

### ISSUE THREAD

**Issue by BrockRiefenstahl** [Morph21/MercuryTrade-Community-Fork#83]
Sometimes when Kicking someone or Closing the Trade Tab causes stuck text in the game (Overlay must be on top of it because the Mouse is not working over it) See screenshot. 

Can this be because I use 2 Monitors? I dont get any errors but every 4rth trade or so the Tool gets stuck like this. And it is really bad, because when I click on it, my movement ingame doesnt work. And once I already died in a bossfight due to this.

This crap infuriates me since years, can someone please fix this?
![Screenshot 2021-08-06 200448 (2)](https://user-images.githubusercontent.com/32821249/128553604-b825ff3c-2380-4914-b04a-e3e522d98a2a.png)

**Comment by Morph21** [comment]
fixed in https://github.com/Morph21/MercuryTrade-Community-Fork/releases/tag/1.2.5
