### ISSUE TITLE
I miss an old feature. Please restore the ability to auto-whisper with a button instead of the instant you copy  the msg.

### ISSUE THREAD

**Issue by EgrenB3S23** [Morph21/MercuryTrade-Community-Fork#84]
I used to be able to copy a trade whisper without MT instantly sending it to he recipient, and then pressing another button later on to actually send the message. Checking the changelog, 1.1.5 has the following description: "Automatic hotkeyless whisper after copy trade message is now available"., but it seems seems to have replaced the old functionality rather than add it as an option.

Is it just me not being able to find the setting, or has this feature really been removed?

**Comment by Morph21** [comment]
There wasn't an option to whisper with button before. You needed to copy message and paste it into chat by yourself and you still can turn off that option in options.
Settings -> Notification panel -> Whisper helper -> turn off enabled checkbox
