### ISSUE TITLE
[BUG] - Item Grid incompaility with widescreen

### ISSUE THREAD

**Issue by womft** [Morph21/MercuryTrade-Community-Fork#85]
**Describe the bug**
Hi,
  this is a carry over problem from the old Mercury Trade, where if the height is <920 the item grid will reset back to some default height ignoring saved settings.

I acknowledge that this problem is probably gonna affect either me or <1% of ppl as i play on a 3840x800 resolution so I dun expect an actual resolution to this "issue" but any guidance will be helpful as I have 0 knowledge on java coding :)

Thanks for taking your time in reading this, hopefully will receive some info soon

Womft

**To Reproduce**
Changing height to <920 & adjusting item grid
item grid resets back to default height

**Expected behavior**
item grid saves the adjusted height settings

**Comment by Morph21** [comment]
Check my last response on #60 let me know if that workaround works for you

**Comment by womft** [comment]
> Check my last response on #60 let me know if that workaround works for you

Holy moley thanks my dude it solved it :D
