### ISSUE TITLE
[BUG] - The currency icon is not displayed on ui.

### ISSUE THREAD

**Issue by newfishq1w2** [Morph21/MercuryTrade-Community-Fork#86]
Hi,
When others buy my items, the currency icon(all currencies except chaos) on the pop-up window is not displayed.  
but this won't happen during the test.
![bug1](https://user-images.githubusercontent.com/85087587/132460662-482bcf28-19f4-4b6c-8298-cf5af3bd3ad9.png)

**Comment by Morph21** [comment]
What website do you use for trading?

**Comment by Morph21** [comment]
Fixed with release https://github.com/Morph21/MercuryTrade-Community-Fork/releases/tag/1.2.0
(when icon won't be found the text will be displayed instead)

**Comment by newfishq1w2** [comment]
Thanks, the problem has been solved.
