### ISSUE TITLE
[BUG] - No way to select path to POE in macOS Mojave via Steam

### ISSUE THREAD

**Issue by ryandagg** [Morph21/MercuryTrade-Community-Fork#87]
**Describe the bug**
It is not possible to select the path during setup. Maybe only under these circumstances:
* macOS Mojave Version 10.14.6
* Have downloaded and launched app via Steam.

**To Reproduce**
1. Download MercuryTrade.jar.zip from here: https://github.com/Morph21/MercuryTrade-Community-Fork/releases
2. unzip file
3. open MercuryJTrade.jar
4. Get the overlay with text of "Select game path..."
5. Click "Select"
6. Navigate to POE location, in my case: ~/Library/Application Support/Steam/steamapps/common/Path of Exile/PathOfExileClient.app

**Expected behavior**
Some path is selectable and leads to the app working.

**Screenshots**
When attempting to select PathOfExileClient.app:
![image](https://user-images.githubusercontent.com/6306282/132721235-fe2a086a-9411-4986-89fe-17b5a2d2bd96.png)

When selecting the parent folder of PathOfExileClient.app:
![image](https://user-images.githubusercontent.com/6306282/132721355-c5823132-77f4-4609-8f94-d4e1969f904a.png)

**Desktop (please complete the following information):**
 - OSX Version 1.0

**Additional context**
Steam package versions: 1626824053
Path of Exile was running when the screenshots were taken.

**Comment by Morph21** [comment]
That error occur only when it didn't find the log file

there is used a function like this:

private boolean isValidGamePath(String gamePath) {
        File file = new File(gamePath + File.separator + "logs" + File.separator + "Client.txt");
        return file.exists();
}

so basically you need to select a path for your logs file of POE.

I'm not sure how it looks on mac os since I don't have one.

Let me know when you will find your Client.txt file on mac

on windows it's in folders like this
C:\\Program Files (x86)\\Grinding Gear Games\\Path of Exile\\logs\\Client.txt

**Comment by seijioulook** [comment]
The path for the Client.txt log file in Mac is:

`$HOME/Library/Caches/com.GGG.PathOfExile/Logs/Client.txt`

I would love to use Mercury on my Mac, can I do something in my Mac to make Mercury work?

**Comment by Morph21** [comment]
Set your game path to $HOME/Library/Caches/com.GGG.PathOfExile/
And let me know if any errors will occur. It's hard to say for me if it will work on Mac

**Comment by Morph21** [comment]
Since newest version it should work or run at least if you set game path to $HOME/Library/Caches/com.GGG.PathOfExile

I'm not sure if everything will work though. I don't have Mac os to test it, so let me know
