### ISSUE TITLE
[BUG] - program bugs out whenever it reads messages pasted from poemap.live

### ISSUE THREAD

**Issue by ediotism** [Morph21/MercuryTrade-Community-Fork#88]
**Describe the bug**
when you send or receive a map-swapping message in game, mercury stops working after. I suspect it's due to the message having a ":" symbol

**To Reproduce**
1. Go to www.poemap.live
2. generate a map swapping request message
3. go to game client and paste the message to send
4. now mercurytrade fails to operate

**Comment by Morph21** [comment]
Can you post an example of that message here?

**Comment by Morph21** [comment]
I guess that poemap.live is dead now so that issue won't be fixed
