### ISSUE TITLE
[BUG] - Panel doesn't close on kick

### ISSUE THREAD

**Issue by thebeast792** [Morph21/MercuryTrade-Community-Fork#9]
**Describe the bug**
When I use the new feature kick/leave for incoming notifications, it does kick the person successfully but it doesn't close the panel. This is with the setting "Close panel on kick" set to enabled.

**To Reproduce**
1. Set "Close panel on kick" to enabled
2. Set kick/leave option for a response button under the Incoming notifications
3. After inviting someone to a party, click the response button
4. The party member gets kicked with the message that the response button is set to
5. The panel for that trade does not close. Have to click the minus or x button to close it.

**Expected behavior**

**Desktop (please complete the following information):**
- Version 1.10

**Comment by Morph21** [comment]
It seems like it's working ok.

Option "Close panel on kick:" is when you press that minus red icon.

If you want the pop up to be closed after pressing response button you should check "Close notification after click" checkbox, it's next to "Kick/Leave after click"

![image](https://user-images.githubusercontent.com/38075691/96021742-24a68f00-0e50-11eb-86ae-60c02dad854f.png)


But you are right that it's missleading a bit. I need probably rename it,

**Comment by thebeast792** [comment]
Oh my mistake. However, I did notice that it might not be working right with buying kick/leave. It tries to kick the seller instead of leaving the group yourself, so you get an error in the chat about trying to kick the seller.

**Comment by Morph21** [comment]
Yea, i saw. It's already fixed. Will be packed in next release which should be in friday

**Comment by Morph21** [comment]
@thebeast792 is this more readable?

![image](https://user-images.githubusercontent.com/38075691/96030586-78b77080-0e5c-11eb-8159-b71a2540a23a.png)

**Comment by thebeast792** [comment]
ya that works

**Comment by Morph21** [comment]
Okey :)

Your feedback is very appreciated

**Comment by thebeast792** [comment]
I think this may have accidentally gotten reverted in the latest version. It keeps trying to kick the seller.

**Comment by Morph21** [comment]
Hmmm...
It should work like that:
If you got incoming message from someone that want to buy your stuff the there will be a kick button and MT will try to kick him.

If you send message to someone with trade request then leave button will be visible and after pressing it will try to kick yourself.

Is it working like I described above?

**Comment by thebeast792** [comment]
I whisper someone to buy something. Buy it and hit "thanks" button. It tries to kick them from the party instead of myself.

**Comment by Morph21** [comment]
Are you sure that you are using right version?

I just tested it out in poe and it's working for me

**Comment by thebeast792** [comment]
Yeah, it has the grid aligner clear button and the vulkan support. I redownloaded the app version here https://github.com/Morph21/MercuryTrade-Community-Fork/releases/tag/1.1.2 but I noticed the about section in the actual app says 1.1.1.

**Comment by Morph21** [comment]
Yea, i did forget to update version number in "about section"

Also about that leave function you should check  if you did set up name of your character in settings -> Notification panel
Becouse in PoE leave from party is essentialy "/kick yourCharNickname"

![image](https://user-images.githubusercontent.com/38075691/96503108-0fb46c00-1253-11eb-87ec-ac9e62b19997.png)

**Comment by thebeast792** [comment]
Oh you're right. That's what I was doing wrong. Sorry!

**Comment by Morph21** [comment]
No problem mate. I'm glad that I could help.

Thanks for your feedback! keep up the good work 👍
