### ISSUE TITLE
How to completely hide taskbar and make flask bars thinner?

### ISSUE THREAD

**Issue by mataski** [Morph21/MercuryTrade-Community-Fork#90]
I already have opacity at lowest. Any way to completely hide default taskbar with 4 icons and only make it open with lets say a shortcut key?

Also anyway to make flasks progress bars smaller/thinner/reduce height?

Also anyway instead of timer use the actual static flask title on the bar? Icon isn't enough if you keep changing flask setup.

Thanks.

**Comment by Morph21** [comment]
1. About hiding default taskbar there will be a new option in next release.
2. You can change width and height is 10px height not small enough for you?
![image](https://user-images.githubusercontent.com/38075691/162841358-cd147cfb-9b3a-4c3b-a44a-48bad2706a92.png)

3. I'm not sure about that one, you can add your own images etc. What you want here?

**Comment by mataski** [comment]
All good, thanks for great tool.

**Comment by Morph21** [comment]
fixed in https://github.com/Morph21/MercuryTrade-Community-Fork/releases/tag/1.2.5
